// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rllefezwuxszkadzadun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbGVmZXp3dXhzemthZHphZHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDI2OTQsImV4cCI6MjA1OTA3ODY5NH0.Q301W7CTefwT2xsHvUk9auTw3uM4kU8SdYhZzYCgbmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);